version: "3.9"
services:
  mysql_db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    hostname: arrivo_mysql_db
    container_name: arrivo_mysql_db
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    env_file: .env